

server:
  port: 8090
management:
  auditevents:
    enabled: true
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/dasu
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

jwt:
  secret: myfirstsecretrandomvariables