

server:
  port: 8080

jwt:
  secret: myfirstsecretrandomvariables


spring:
  main:
    web-application-type: reactive

  ### DB 설정 ###
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/dasu
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  ### Gateway 설정
  cloud:
    gateway:
      routes:
        - id: authentication-server
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
          filters:
            - AddRequestHeader=From-Gateway, true
        - id: monitoring-server
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
          filters:
            - AddRequestHeader=From-Gateway, true
            - StripPrefix=1
  boot:
    admin:
      client:
        url: http://localhost:8081
  application:
    name: gateway-server

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.springframework.security: DEBUG